---
stages:
- name: Build Stage
  inputs:
  - url: {{REPO}}
    type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy Services
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    script: |
      #!/bin/bash
      cf create-service natural_language_classifier standard NaturalLanguageClassifier
      cf create-service businessrules standard BusinessRules
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy application
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    script: |
      #!/bin/bash
      cf push "${CF_APP}"
      # View logs
      cf logs "${CF_APP}" --recent
